# Generated by Django 4.2.8 on 2023-12-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('prod', models.CharField(max_length=50)),
                ('prc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quan', models.IntegerField(default=1)),
                ('img', models.ImageField(upload_to='images/')),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.IntegerField(default=1)),
                ('img1', models.ImageField(upload_to='images/')),
                ('des1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
